# SPDX-FileCopyrightText: 2023 Junde Yhi <junde@yhi.moe>
# SPDX-License-Identifier: CC0-1.0

FROM debian

# Install the latest GNAT, GPRbuild and Alire from Debian. Alire depends on
# cURL and Git to download packages and the index.
RUN apt-get update && \
apt-get install -y gnat gprbuild curl git alire && \
rm -rf /var/lib/apt/lists/*

# Stop Alire from interactively asking for a selection of toolchain.
RUN alr toolchain --disable-assistant
